# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs


Tag.create([
               {:name => "education", :image => nil, :created_at => "2013-09-10 11:22:23", :updated_at => "2013-09-10 11:22:23", :disabled => false, :active_count => 0},
               {:name => "sport", :image => nil, :created_at => "2013-09-10 11:24:06", :updated_at => "2013-09-10 11:24:06", :disabled => false, :active_count => 0},
               {:name => "travel", :image => nil, :created_at => "2013-09-10 11:25:45", :updated_at => "2013-09-10 11:25:45", :disabled => false, :active_count => 0}
           ], :without_protection => true)


User.create([
                {:first => "andrew", :last => "nazymko", :e_mail => "some@e.mail", :password => "24f0d2c90473b2bc949ad962e61d9bcb", :login => "core_admin", :created_at => "2013-09-10 11:15:47", :updated_at => "2013-09-10 11:15:47", :role => "core_admin"},
                {:first => "super", :last => "user", :e_mail => "some@e.mail", :password => "24f0d2c90473b2bc949ad962e61d9bcb", :login => "admin", :created_at => "2013-09-10 11:15:47", :updated_at => "2013-09-10 11:15:47", :role => "admin"},
                {:first => "Jo", :last => "Kamton", :e_mail => "dieg0@gmail.com", :password => "24f0d2c90473b2bc949ad962e61d9bcb", :login => "diego", :created_at => "2013-09-10 11:15:47", :updated_at => "2013-09-10 11:15:47", :role => "subscriber"}
            ], :without_protection => true)


